{
 "title": "Adguard Exporter",
 "description": "This is a Adguard dashboard when using the https://github.com/ebrianne/adguard-exporter Prometheus exporter",
 "tags": [ "adguard" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(adguard_exporter_build_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "AdGuard Home",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_exporter_build_info{instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Protection",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_exporter_build_info{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Processing TIme",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "adguard_stats{instance=~\"$node\",name=\"avg_processing_time\"}",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "Number of queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_stats{name=\"num_dns_queries\", instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Number of queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_stats{name=\"num_dns_queries\", instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Percent of ads blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_stats{instance=~\"$node\",name=\"num_blocked_filtering\"} / ignoring(name) adguard_stats{instance=~\"$node\",name=\"num_dns_queries\"} * 100"
    }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "adguard_top_queried_domains{instance=~\"$node\"}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "adguard_top_blocked_domains{instance=~\"$node\"}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Filtering Rules Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(adguard_filtering_status{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Adguard Home Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "adguard_exporter_build_info{instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "adguard_exporter_build_info{instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Query Types",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_dns_query_types{instance=~\"$node\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_stats{instance=~\"$node\",name=\"num_dns_queries\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "adguard_dns_query_types{instance=~\"$node\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Top clients by source",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "adguard_top_clients{instance=~\"$node\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Ads blocked",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_stats{instance=~\"$node\",name=\"num_blocked_filtering\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Top clients",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_top_clients{instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_top_blocked_domains{instance=~\"$node\"}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "adguard_stats{instance=~\"$node\",name=\"num_blocked_filtering\"} / ignoring(name) adguard_stats{instance=~\"$node\",name=\"num_dns_queries\"} * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Top queries",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_top_queried_domains{instance=~\"$node\"}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Filtering Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_filtering_status{instance=~\"$node\"}",
     "legendFormat": "{{ domain }}"
    }
   ]
  }
 ]
}